# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rehberpencere.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FORM(object):
    def setupUi(self, FORM):
        FORM.setObjectName("FORM")
        FORM.resize(538, 580)
        FORM.setStyleSheet("QWidget{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton {\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QMainWindow{\n"
"    \n"
"background-image: url(:/arkaplan/image/arkaplan/7.jpg);\n"
"background-repeat : no-repeat;\n"
"/*background-position : center;*/\n"
"background-attachment :fixed;\n"
"background-origin : content\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"background-color : none;    \n"
"color: rgb(240, 233, 221);\n"
"    \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton500 = QtWidgets.QPushButton(FORM)
        self.pushButton500.setGeometry(QtCore.QRect(110, 260, 41, 41))
        self.pushButton500.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/ayarlar_bildirim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton500.setIcon(icon)
        self.pushButton500.setIconSize(QtCore.QSize(25, 25))
        self.pushButton500.setObjectName("pushButton500")
        self.pushButton_505 = QtWidgets.QPushButton(FORM)
        self.pushButton_505.setGeometry(QtCore.QRect(10, 260, 41, 41))
        self.pushButton_505.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/icon/ayarlar_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_505.setIcon(icon1)
        self.pushButton_505.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_505.setObjectName("pushButton_505")
        self.pushButton_507 = QtWidgets.QPushButton(FORM)
        self.pushButton_507.setGeometry(QtCore.QRect(10, 460, 41, 41))
        self.pushButton_507.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/icon/ses_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_507.setIcon(icon2)
        self.pushButton_507.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_507.setObjectName("pushButton_507")
        self.pushButton_508 = QtWidgets.QPushButton(FORM)
        self.pushButton_508.setGeometry(QtCore.QRect(60, 460, 41, 41))
        self.pushButton_508.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/simge/image/icon/ses_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_508.setIcon(icon3)
        self.pushButton_508.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_508.setObjectName("pushButton_508")
        self.pushButton_511 = QtWidgets.QPushButton(FORM)
        self.pushButton_511.setGeometry(QtCore.QRect(10, 60, 41, 41))
        self.pushButton_511.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/icon/cevrimdisi_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_511.setIcon(icon4)
        self.pushButton_511.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_511.setObjectName("pushButton_511")
        self.pushButton_512 = QtWidgets.QPushButton(FORM)
        self.pushButton_512.setGeometry(QtCore.QRect(60, 60, 41, 41))
        self.pushButton_512.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/icon/cevrimdisi_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_512.setIcon(icon5)
        self.pushButton_512.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_512.setObjectName("pushButton_512")
        self.pushButton_513 = QtWidgets.QPushButton(FORM)
        self.pushButton_513.setGeometry(QtCore.QRect(10, 310, 41, 41))
        self.pushButton_513.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image/icon/ilerleme_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_513.setIcon(icon6)
        self.pushButton_513.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_513.setObjectName("pushButton_513")
        self.pushButton_514 = QtWidgets.QPushButton(FORM)
        self.pushButton_514.setGeometry(QtCore.QRect(60, 310, 41, 41))
        self.pushButton_514.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("image/icon/ilerleme_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_514.setIcon(icon7)
        self.pushButton_514.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_514.setObjectName("pushButton_514")
        self.pushButton_501 = QtWidgets.QPushButton(FORM)
        self.pushButton_501.setGeometry(QtCore.QRect(10, 210, 41, 41))
        self.pushButton_501.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("image/icon/bilgi_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_501.setIcon(icon8)
        self.pushButton_501.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_501.setObjectName("pushButton_501")
        self.pushButton_503 = QtWidgets.QPushButton(FORM)
        self.pushButton_503.setGeometry(QtCore.QRect(60, 210, 41, 41))
        self.pushButton_503.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("image/icon/bilgi_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_503.setIcon(icon9)
        self.pushButton_503.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_503.setObjectName("pushButton_503")
        self.pushButton_502 = QtWidgets.QPushButton(FORM)
        self.pushButton_502.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.pushButton_502.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("image/icon/mod_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_502.setIcon(icon10)
        self.pushButton_502.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_502.setObjectName("pushButton_502")
        self.pushButton_510 = QtWidgets.QPushButton(FORM)
        self.pushButton_510.setGeometry(QtCore.QRect(60, 10, 41, 41))
        self.pushButton_510.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("image/icon/mod_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_510.setIcon(icon11)
        self.pushButton_510.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_510.setObjectName("pushButton_510")
        self.pushButton_506 = QtWidgets.QPushButton(FORM)
        self.pushButton_506.setGeometry(QtCore.QRect(60, 260, 41, 41))
        self.pushButton_506.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("image/icon/ayarlar_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_506.setIcon(icon12)
        self.pushButton_506.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_506.setObjectName("pushButton_506")
        self.pushButton_509 = QtWidgets.QPushButton(FORM)
        self.pushButton_509.setGeometry(QtCore.QRect(110, 310, 41, 41))
        self.pushButton_509.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("image/icon/ilerleme_bildirim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_509.setIcon(icon13)
        self.pushButton_509.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_509.setObjectName("pushButton_509")
        self.label_rehber_mod = QtWidgets.QLabel(FORM)
        self.label_rehber_mod.setGeometry(QtCore.QRect(110, 20, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rehber_mod.setFont(font)
        self.label_rehber_mod.setObjectName("label_rehber_mod")
        self.label_rehber_cevrimdisi = QtWidgets.QLabel(FORM)
        self.label_rehber_cevrimdisi.setGeometry(QtCore.QRect(110, 70, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rehber_cevrimdisi.setFont(font)
        self.label_rehber_cevrimdisi.setObjectName("label_rehber_cevrimdisi")
        self.label_rehber_bilgi = QtWidgets.QLabel(FORM)
        self.label_rehber_bilgi.setGeometry(QtCore.QRect(110, 220, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rehber_bilgi.setFont(font)
        self.label_rehber_bilgi.setObjectName("label_rehber_bilgi")
        self.label_rehber_ayarlar = QtWidgets.QLabel(FORM)
        self.label_rehber_ayarlar.setGeometry(QtCore.QRect(160, 270, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rehber_ayarlar.setFont(font)
        self.label_rehber_ayarlar.setObjectName("label_rehber_ayarlar")
        self.label_rehber_guncelleme = QtWidgets.QLabel(FORM)
        self.label_rehber_guncelleme.setGeometry(QtCore.QRect(160, 320, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rehber_guncelleme.setFont(font)
        self.label_rehber_guncelleme.setObjectName("label_rehber_guncelleme")
        self.label_rehber_champses = QtWidgets.QLabel(FORM)
        self.label_rehber_champses.setGeometry(QtCore.QRect(110, 470, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rehber_champses.setFont(font)
        self.label_rehber_champses.setObjectName("label_rehber_champses")
        self.label_rehber_aciklama_cevrimici = QtWidgets.QLabel(FORM)
        self.label_rehber_aciklama_cevrimici.setGeometry(QtCore.QRect(10, 120, 501, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_rehber_aciklama_cevrimici.setFont(font)
        self.label_rehber_aciklama_cevrimici.setObjectName("label_rehber_aciklama_cevrimici")
        self.label_rehber_aciklama_guncelleme = QtWidgets.QLabel(FORM)
        self.label_rehber_aciklama_guncelleme.setGeometry(QtCore.QRect(10, 360, 511, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_rehber_aciklama_guncelleme.setFont(font)
        self.label_rehber_aciklama_guncelleme.setObjectName("label_rehber_aciklama_guncelleme")
        self.label_rehber_kaynak = QtWidgets.QLabel(FORM)
        self.label_rehber_kaynak.setGeometry(QtCore.QRect(130, 560, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_rehber_kaynak.setFont(font)
        self.label_rehber_kaynak.setObjectName("label_rehber_kaynak")
        self.pushButton_515 = QtWidgets.QPushButton(FORM)
        self.pushButton_515.setGeometry(QtCore.QRect(60, 510, 41, 41))
        self.pushButton_515.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("image/icon/arama_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_515.setIcon(icon14)
        self.pushButton_515.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_515.setObjectName("pushButton_515")
        self.label_rehber_arama = QtWidgets.QLabel(FORM)
        self.label_rehber_arama.setGeometry(QtCore.QRect(110, 520, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rehber_arama.setFont(font)
        self.label_rehber_arama.setObjectName("label_rehber_arama")
        self.pushButton_516 = QtWidgets.QPushButton(FORM)
        self.pushButton_516.setGeometry(QtCore.QRect(10, 510, 41, 41))
        self.pushButton_516.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("image/icon/arama_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_516.setIcon(icon15)
        self.pushButton_516.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_516.setObjectName("pushButton_516")

        self.retranslateUi(FORM)
        QtCore.QMetaObject.connectSlotsByName(FORM)

    def retranslateUi(self, FORM):
        _translate = QtCore.QCoreApplication.translate
        FORM.setWindowTitle(_translate("FORM", "REHBER"))
        self.label_rehber_mod.setText(_translate("FORM", "Diğer oyun modu istatistikleri  -->  Kapalı - Açık"))
        self.label_rehber_cevrimdisi.setText(_translate("FORM", "Çevrimiçi veri kullanımı  -->  Kapalı - Açık"))
        self.label_rehber_bilgi.setText(_translate("FORM", "Bilgilendirme  -->  Kapalı - Açık"))
        self.label_rehber_ayarlar.setText(_translate("FORM", "Ayarlar  -->  Kapalı - Açık - Güncelleniyor"))
        self.label_rehber_guncelleme.setText(_translate("FORM", "Veri güncelleme durumu  -->  Kapalı - Açık - Güncelleniyor"))
        self.label_rehber_champses.setText(_translate("FORM", "Şampiyon seçim sesleri  -->  Kapalı - Açık"))
        self.label_rehber_aciklama_cevrimici.setText(_translate("FORM", "Çevrimdışı Modu : Verileri bir kez güncelledikten sonra bu modu kullanmak uygulamanın veri\n"
"analizi yaparkenki hızını büyük ölçüde arttırır fakat daha önce kaydedilen\n"
"veriyi göstereceği için gelen yama istatistiklerini yansıtmayabilir.\n"
"Çevrimiçi Modu : Sürekli güncel bilgilere erişim sağlar ama verilerin işlenmesi sırasında bir kaç \n"
"saniyelik gecikmeler yaşanabilir."))
        self.label_rehber_aciklama_guncelleme.setText(_translate("FORM", "Güncelleme sırasında veri yedeklemenin hangi durumda olduğunu görmek için ayarlar\n"
"sekmesinin altındaki güncelleme çubuğu takip edilebilir.Ayarlar ve güncelleme butonunun\n"
"simgesinin maviye dönmesi veri güncellemesi yaptığının kullanıcıya bildirilmesi anlamına gelir.\n"
"Güncellemeyi uygulamanın her açılışında otomatik olarak yapması için Otomatik Güncelle\n"
"seçeneğini seçebilir, yada bunu devre dışı bırarak istediğiniz zaman güncellemek yapmak için\n"
"Manuel Güncelle Butonunu kullanabilirsiniz"))
        self.label_rehber_kaynak.setText(_translate("FORM", "Veriler; https://leagueoflegends.fandom.com adresinden alınmaktadır."))
        self.label_rehber_arama.setText(_translate("FORM", "Şampiyon arama  -->  Kapalı - Açık"))
import image_koleksiyon_rc
