# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statstasarim.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 515)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    \n"
"background-image: url(:/arkaplan/image/arkaplan/7.jpg);\n"
"background-repeat : no-repeat;\n"
"/*background-position : center;*/\n"
"background-attachment :fixed;\n"
"background-origin : content\n"
"}\n"
"\n"
"QLabel{\n"
"background-color : none;    \n"
"color: rgb(240, 233, 221);\n"
"}\n"
"QFrame{\n"
"background-color : none;\n"
"}\n"
"QRadioButton{\n"
"color: rgb(240, 233, 221);\n"
"}\n"
"QCheckBox {\n"
"color: rgb(240, 233, 221);\n"
"    font: 75 8pt \"Microsoft Tai Le\";\n"
"\n"
"}\n"
"QScrollArea{\n"
"background-color : none;\n"
"}\n"
"QWidget{\n"
"background-color : none\n"
"}\n"
"\n"
"QMessageBox{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton {\n"
"\n"
"background-color:initial;\n"
"}\n"
"\n"
"\n"
"QProgressBar{\n"
"background-color: transparent;\n"
"border: 3px solid rgb(210, 227, 148) ;\n"
"border-radius: 9px;\n"
"text-align: center;\n"
"color: rgb(210, 227, 148);\n"
"font: 87 16pt \"Segoe UI Black\";\n"
"\n"
"}/*eğer çubuğun rengini değiştirmek istiyorsan buranın yorumunu kaldır. köşeli olmamasınıda böyle yapabiliyosun*/\n"
"QProgressBar::chunk {\n"
"background-color: rgb(46, 121, 5);\n"
"border-radius:9px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*SCROLBARR AYARLARI*/\n"
"QScrollBar{\n"
"\n"
"}\n"
"/*VERTİCAL SCROLLBAR*/\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 19px;\n"
"    margin: 15px 0 15px 0 ;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:1.89413e-06, fx:0.5, fy:0.5, stop:0 rgba(198, 191, 100, 255), stop:0.585227 rgba(80, 81, 17, 255), stop:1 rgba(25, 24, 16, 255));\n"
"    min-width: 20px;\n"
"    min-height:35px;\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:1.89413e-06, fx:0.5, fy:0.5, stop:0 rgba(198, 191, 100, 255), stop:0.585227 rgba(80, 81, 17, 255), stop:1 rgba(25, 24, 16, 255));\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {\n"
"    \n"
"    background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:1.89413e-06, fx:0.5, fy:0.5, stop:0 rgba(163, 100, 198, 255), stop:0.585227 rgba(58, 17, 81, 255), stop:1 rgba(25, 24, 16, 255));\n"
"} \n"
"/*BTN TOP - SCROLLBAR*/\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    ;\n"
"    background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:1.89413e-06, fx:0.5, fy:0.5, stop:0 rgba(198, 191, 100, 255), stop:0.585227 rgba(80, 81, 17, 255), stop:1 rgba(25, 24, 16, 255));\n"
"    height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"/*BTN BOTTOM - SCROLLBAR*/\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    \n"
"    background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:1.89413e-06, fx:0.5, fy:0.5, stop:0 rgba(198, 191, 100, 255), stop:0.585227 rgba(80, 81, 17, 255), stop:1 rgba(25, 24, 16, 255));\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"/*SCROLLAREA WİDGETİNİN ARKA PLANLA UYUMLU OLMASI İÇİN*/\n"
"QAbstractScrollArea{\n"
"background-color: transparent;\n"
"}\n"
"QWidget#scrollAreaWidgetContents{\n"
"background-color: transparent\n"
"}\n"
"\n"
"\n"
"/*KAYDIRMA ÇUBUĞU YOLUNUN ARKA PLANLA UYUMLU OLMASI İÇİN*/\n"
"QScrollBar{\n"
"background-color: transparent\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background-color: transparent\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 3px solid rgb(210, 227, 148);\n"
"    border-radius : 8px;\n"
"    height: 15px; /* yükseklik */\n"
"    background: transparent;\n"
"    margin: 0px0 ; /*sliderin çerçeve kısmı tutumaç kısmından büyük olmasını istiyorsan bu kısmı 3px0 olarak falan değiştirebilirsin*/\n"
"    position: absolute;\n"
"    left: 1px; right: 1px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color:rgb(210, 227, 148);\n"
"    border: 1px solid rgb(32, 90, 25);\n"
"    width: 10px;\n"
"    margin: 0px 0; \n"
"    border-radius: 6px;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(170, 255, 255);\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"background: transparent;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"background: transparent;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea_camp = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_camp.setEnabled(True)
        self.scrollArea_camp.setGeometry(QtCore.QRect(20, 20, 161, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.scrollArea_camp.setPalette(palette)
        self.scrollArea_camp.setAutoFillBackground(True)
        self.scrollArea_camp.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
" border-width: 0px\n"
";border-radius: 10px;\n"
"border-color: rgb(136, 136, 68) ;\n"
" text-align: left ;\n"
" font: 57 10pt \"Dubai Medium\"; \n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:1.4, stop:0 rgba(242, 232, 151, 255), stop:0.0735931 rgba(234, 225, 98, 255), stop:0.16 rgba(217, 206, 70, 255), stop:0.225 rgba(232, 230, 162, 255), stop:0.285 rgba(227, 214, 86, 255), stop:0.345 rgba(235, 230, 189, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.45671 rgba(231, 218, 98, 255), stop:0.52 rgba(237, 226, 113, 255), stop:0.57 rgba(226, 223, 56, 255), stop:0.634199 rgba(214, 203, 90, 255), stop:0.695 rgba(229, 221, 157, 255), stop:0.75 rgba(218, 194, 19, 255), stop:0.815 rgba(236, 229, 119, 255), stop:0.88 rgba(239, 235, 185, 255), stop:0.935 rgba(232, 229, 139, 255), stop:1 rgba(238, 225, 81, 255));\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(210, 227, 148);\n"
"}")
        self.scrollArea_camp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_camp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_camp.setLineWidth(2)
        self.scrollArea_camp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_camp.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_camp.setWidgetResizable(True)
        self.scrollArea_camp.setObjectName("scrollArea_camp")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 142, 321))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_camp.setWidget(self.scrollAreaWidgetContents)
        self.frame_info = QtWidgets.QFrame(self.centralwidget)
        self.frame_info.setGeometry(QtCore.QRect(200, 20, 901, 371))
        self.frame_info.setStyleSheet("\n"
"border-radius: 10px")
        self.frame_info.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_info.setLineWidth(2)
        self.frame_info.setObjectName("frame_info")
        self.layoutWidget = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 121, 53))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_mana = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_mana.setFont(font)
        self.label_mana.setObjectName("label_mana")
        self.verticalLayout_2.addWidget(self.label_mana)
        self.label_mana_deger = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_mana_deger.setFont(font)
        self.label_mana_deger.setText("")
        self.label_mana_deger.setObjectName("label_mana_deger")
        self.verticalLayout_2.addWidget(self.label_mana_deger)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 130, 131, 53))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_saldirigucu = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirigucu.setFont(font)
        self.label_saldirigucu.setObjectName("label_saldirigucu")
        self.verticalLayout_3.addWidget(self.label_saldirigucu)
        self.label_saldirigucu_deger = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirigucu_deger.setFont(font)
        self.label_saldirigucu_deger.setText("")
        self.label_saldirigucu_deger.setObjectName("label_saldirigucu_deger")
        self.verticalLayout_3.addWidget(self.label_saldirigucu_deger)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_3.setGeometry(QtCore.QRect(170, 130, 171, 54))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_kritiksansi = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_kritiksansi.setFont(font)
        self.label_kritiksansi.setObjectName("label_kritiksansi")
        self.verticalLayout_9.addWidget(self.label_kritiksansi)
        self.label_kritiksansi_deger = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_kritiksansi_deger.setFont(font)
        self.label_kritiksansi_deger.setText("")
        self.label_kritiksansi_deger.setObjectName("label_kritiksansi_deger")
        self.verticalLayout_9.addWidget(self.label_kritiksansi_deger)
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 190, 121, 53))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_harekethizi = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_harekethizi.setFont(font)
        self.label_harekethizi.setObjectName("label_harekethizi")
        self.verticalLayout_4.addWidget(self.label_harekethizi)
        self.label_harekethizi_deger = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_harekethizi_deger.setFont(font)
        self.label_harekethizi_deger.setText("")
        self.label_harekethizi_deger.setObjectName("label_harekethizi_deger")
        self.verticalLayout_4.addWidget(self.label_harekethizi_deger)
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_5.setGeometry(QtCore.QRect(170, 190, 171, 53))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_saldirimenzili = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirimenzili.setFont(font)
        self.label_saldirimenzili.setObjectName("label_saldirimenzili")
        self.verticalLayout_10.addWidget(self.label_saldirimenzili)
        self.label_saldirimenzili_deger = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirimenzili_deger.setFont(font)
        self.label_saldirimenzili_deger.setText("")
        self.label_saldirimenzili_deger.setObjectName("label_saldirimenzili_deger")
        self.verticalLayout_10.addWidget(self.label_saldirimenzili_deger)
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 310, 131, 53))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_buyudirenci = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_buyudirenci.setFont(font)
        self.label_buyudirenci.setObjectName("label_buyudirenci")
        self.verticalLayout_6.addWidget(self.label_buyudirenci)
        self.label_buyudirenci_deger = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_buyudirenci_deger.setFont(font)
        self.label_buyudirenci_deger.setText("")
        self.label_buyudirenci_deger.setObjectName("label_buyudirenci_deger")
        self.verticalLayout_6.addWidget(self.label_buyudirenci_deger)
        self.layoutWidget_7 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_7.setGeometry(QtCore.QRect(170, 310, 171, 53))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_saldirihiziorani = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirihiziorani.setFont(font)
        self.label_saldirihiziorani.setObjectName("label_saldirihiziorani")
        self.verticalLayout_12.addWidget(self.label_saldirihiziorani)
        self.label_saldirihiziorani_deger = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirihiziorani_deger.setFont(font)
        self.label_saldirihiziorani_deger.setText("")
        self.label_saldirihiziorani_deger.setObjectName("label_saldirihiziorani_deger")
        self.verticalLayout_12.addWidget(self.label_saldirihiziorani_deger)
        self.layoutWidget_8 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_8.setGeometry(QtCore.QRect(170, 250, 171, 53))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_temelsaldirihizi = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_temelsaldirihizi.setFont(font)
        self.label_temelsaldirihizi.setObjectName("label_temelsaldirihizi")
        self.verticalLayout_11.addWidget(self.label_temelsaldirihizi)
        self.label_temelsaldirihizi_deger = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_temelsaldirihizi_deger.setFont(font)
        self.label_temelsaldirihizi_deger.setText("")
        self.label_temelsaldirihizi_deger.setObjectName("label_temelsaldirihizi_deger")
        self.verticalLayout_11.addWidget(self.label_temelsaldirihizi_deger)
        self.layoutWidget_9 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_9.setGeometry(QtCore.QRect(170, 70, 171, 53))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_manayenileme = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_manayenileme.setFont(font)
        self.label_manayenileme.setObjectName("label_manayenileme")
        self.verticalLayout_8.addWidget(self.label_manayenileme)
        self.label_manayenileme_deger = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_manayenileme_deger.setFont(font)
        self.label_manayenileme_deger.setText("")
        self.label_manayenileme_deger.setObjectName("label_manayenileme_deger")
        self.verticalLayout_8.addWidget(self.label_manayenileme_deger)
        self.layoutWidget_10 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_10.setGeometry(QtCore.QRect(170, 10, 171, 53))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_canyenileme = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_canyenileme.setFont(font)
        self.label_canyenileme.setObjectName("label_canyenileme")
        self.verticalLayout_7.addWidget(self.label_canyenileme)
        self.label_canyenileme_deger = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_canyenileme_deger.setFont(font)
        self.label_canyenileme_deger.setText("")
        self.label_canyenileme_deger.setObjectName("label_canyenileme_deger")
        self.verticalLayout_7.addWidget(self.label_canyenileme_deger)
        self.layoutWidget_11 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 250, 111, 53))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_zirh = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_zirh.setFont(font)
        self.label_zirh.setObjectName("label_zirh")
        self.verticalLayout_5.addWidget(self.label_zirh)
        self.label_zirh_deger = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_zirh_deger.setFont(font)
        self.label_zirh_deger.setText("")
        self.label_zirh_deger.setObjectName("label_zirh_deger")
        self.verticalLayout_5.addWidget(self.label_zirh_deger)
        self.layoutWidget_12 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_12.setGeometry(QtCore.QRect(370, 190, 181, 51))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_secimyaricap = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_secimyaricap.setFont(font)
        self.label_secimyaricap.setObjectName("label_secimyaricap")
        self.verticalLayout_16.addWidget(self.label_secimyaricap)
        self.label_secimyaricap_deger = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_secimyaricap_deger.setFont(font)
        self.label_secimyaricap_deger.setText("")
        self.label_secimyaricap_deger.setObjectName("label_secimyaricap_deger")
        self.verticalLayout_16.addWidget(self.label_secimyaricap_deger)
        self.layoutWidget_13 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_13.setGeometry(QtCore.QRect(370, 310, 171, 51))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_edinmeyaricap = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_edinmeyaricap.setFont(font)
        self.label_edinmeyaricap.setObjectName("label_edinmeyaricap")
        self.verticalLayout_18.addWidget(self.label_edinmeyaricap)
        self.label_edinmeyaricap_deger = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_edinmeyaricap_deger.setFont(font)
        self.label_edinmeyaricap_deger.setText("")
        self.label_edinmeyaricap_deger.setObjectName("label_edinmeyaricap_deger")
        self.verticalLayout_18.addWidget(self.label_edinmeyaricap_deger)
        self.layoutWidget_14 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_14.setGeometry(QtCore.QRect(370, 250, 181, 51))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_yolyaricap = QtWidgets.QLabel(self.layoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_yolyaricap.setFont(font)
        self.label_yolyaricap.setObjectName("label_yolyaricap")
        self.verticalLayout_17.addWidget(self.label_yolyaricap)
        self.label_yolyaricap_deger = QtWidgets.QLabel(self.layoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_yolyaricap_deger.setFont(font)
        self.label_yolyaricap_deger.setText("")
        self.label_yolyaricap_deger.setObjectName("label_yolyaricap_deger")
        self.verticalLayout_17.addWidget(self.label_yolyaricap_deger)
        self.layoutWidget_15 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_15.setGeometry(QtCore.QRect(370, 70, 181, 53))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_bonussaldirihizi = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_bonussaldirihizi.setFont(font)
        self.label_bonussaldirihizi.setObjectName("label_bonussaldirihizi")
        self.verticalLayout_14.addWidget(self.label_bonussaldirihizi)
        self.label_bonussaldirihizi_deger = QtWidgets.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_bonussaldirihizi_deger.setFont(font)
        self.label_bonussaldirihizi_deger.setText("")
        self.label_bonussaldirihizi_deger.setObjectName("label_bonussaldirihizi_deger")
        self.verticalLayout_14.addWidget(self.label_bonussaldirihizi_deger)
        self.layoutWidget_16 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_16.setGeometry(QtCore.QRect(370, 10, 182, 53))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_16)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_saldirisonlandirma = QtWidgets.QLabel(self.layoutWidget_16)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirisonlandirma.setFont(font)
        self.label_saldirisonlandirma.setObjectName("label_saldirisonlandirma")
        self.verticalLayout_13.addWidget(self.label_saldirisonlandirma)
        self.label_saldirisonlandirma_deger = QtWidgets.QLabel(self.layoutWidget_16)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_saldirisonlandirma_deger.setFont(font)
        self.label_saldirisonlandirma_deger.setText("")
        self.label_saldirisonlandirma_deger.setObjectName("label_saldirisonlandirma_deger")
        self.verticalLayout_13.addWidget(self.label_saldirisonlandirma_deger)
        self.layoutWidget_17 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget_17.setGeometry(QtCore.QRect(370, 130, 181, 51))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_17)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_oyunyaricap = QtWidgets.QLabel(self.layoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_oyunyaricap.setFont(font)
        self.label_oyunyaricap.setObjectName("label_oyunyaricap")
        self.verticalLayout_15.addWidget(self.label_oyunyaricap)
        self.label_oyunyaricap_deger = QtWidgets.QLabel(self.layoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_oyunyaricap_deger.setFont(font)
        self.label_oyunyaricap_deger.setText("")
        self.label_oyunyaricap_deger.setObjectName("label_oyunyaricap_deger")
        self.verticalLayout_15.addWidget(self.label_oyunyaricap_deger)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_info)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 121, 53))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label_can = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_can.setFont(font)
        self.label_can.setObjectName("label_can")
        self.verticalLayout_1.addWidget(self.label_can)
        self.label_can_deger = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_can_deger.setFont(font)
        self.label_can_deger.setText("")
        self.label_can_deger.setObjectName("label_can_deger")
        self.verticalLayout_1.addWidget(self.label_can_deger)
        self.frame_mod = QtWidgets.QFrame(self.frame_info)
        self.frame_mod.setGeometry(QtCore.QRect(610, 20, 291, 341))
        self.frame_mod.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mod.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mod.setObjectName("frame_mod")
        self.layoutWidget_20 = QtWidgets.QWidget(self.frame_mod)
        self.layoutWidget_20.setGeometry(QtCore.QRect(150, 0, 131, 111))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.layoutWidget_20)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_arena = QtWidgets.QLabel(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_arena.setFont(font)
        self.label_arena.setObjectName("label_arena")
        self.verticalLayout_42.addWidget(self.label_arena)
        self.label_arena_deger = QtWidgets.QLabel(self.layoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arena_deger.sizePolicy().hasHeightForWidth())
        self.label_arena_deger.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_arena_deger.setFont(font)
        self.label_arena_deger.setText("")
        self.label_arena_deger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_arena_deger.setWordWrap(True)
        self.label_arena_deger.setObjectName("label_arena_deger")
        self.verticalLayout_42.addWidget(self.label_arena_deger)
        self.layoutWidget_21 = QtWidgets.QWidget(self.frame_mod)
        self.layoutWidget_21.setGeometry(QtCore.QRect(0, 250, 131, 101))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.layoutWidget_21)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_nexusblitz = QtWidgets.QLabel(self.layoutWidget_21)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_nexusblitz.setFont(font)
        self.label_nexusblitz.setObjectName("label_nexusblitz")
        self.verticalLayout_43.addWidget(self.label_nexusblitz)
        self.label_nexusblitz_deger = QtWidgets.QLabel(self.layoutWidget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nexusblitz_deger.sizePolicy().hasHeightForWidth())
        self.label_nexusblitz_deger.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_nexusblitz_deger.setFont(font)
        self.label_nexusblitz_deger.setText("")
        self.label_nexusblitz_deger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_nexusblitz_deger.setWordWrap(True)
        self.label_nexusblitz_deger.setObjectName("label_nexusblitz_deger")
        self.verticalLayout_43.addWidget(self.label_nexusblitz_deger)
        self.layoutWidget_23 = QtWidgets.QWidget(self.frame_mod)
        self.layoutWidget_23.setGeometry(QtCore.QRect(150, 250, 133, 101))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.layoutWidget_23)
        self.verticalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_ultibuyukitabi = QtWidgets.QLabel(self.layoutWidget_23)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_ultibuyukitabi.setFont(font)
        self.label_ultibuyukitabi.setObjectName("label_ultibuyukitabi")
        self.verticalLayout_45.addWidget(self.label_ultibuyukitabi)
        self.label_ultibuyukitabi_deger = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ultibuyukitabi_deger.sizePolicy().hasHeightForWidth())
        self.label_ultibuyukitabi_deger.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_ultibuyukitabi_deger.setFont(font)
        self.label_ultibuyukitabi_deger.setText("")
        self.label_ultibuyukitabi_deger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_ultibuyukitabi_deger.setWordWrap(True)
        self.label_ultibuyukitabi_deger.setObjectName("label_ultibuyukitabi_deger")
        self.verticalLayout_45.addWidget(self.label_ultibuyukitabi_deger)
        self.layoutWidget_19 = QtWidgets.QWidget(self.frame_mod)
        self.layoutWidget_19.setGeometry(QtCore.QRect(0, 130, 131, 101))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_urf = QtWidgets.QLabel(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_urf.setFont(font)
        self.label_urf.setObjectName("label_urf")
        self.verticalLayout_41.addWidget(self.label_urf)
        self.label_urf_deger = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_urf_deger.sizePolicy().hasHeightForWidth())
        self.label_urf_deger.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_urf_deger.setFont(font)
        self.label_urf_deger.setText("")
        self.label_urf_deger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_urf_deger.setWordWrap(True)
        self.label_urf_deger.setObjectName("label_urf_deger")
        self.verticalLayout_41.addWidget(self.label_urf_deger)
        self.layoutWidget_22 = QtWidgets.QWidget(self.frame_mod)
        self.layoutWidget_22.setGeometry(QtCore.QRect(150, 130, 141, 101))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.layoutWidget_22)
        self.verticalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_birimizhepimizicin = QtWidgets.QLabel(self.layoutWidget_22)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_birimizhepimizicin.setFont(font)
        self.label_birimizhepimizicin.setObjectName("label_birimizhepimizicin")
        self.verticalLayout_44.addWidget(self.label_birimizhepimizicin)
        self.label_birimizhepimizicin_deger = QtWidgets.QLabel(self.layoutWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_birimizhepimizicin_deger.sizePolicy().hasHeightForWidth())
        self.label_birimizhepimizicin_deger.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_birimizhepimizicin_deger.setFont(font)
        self.label_birimizhepimizicin_deger.setText("")
        self.label_birimizhepimizicin_deger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_birimizhepimizicin_deger.setWordWrap(True)
        self.label_birimizhepimizicin_deger.setObjectName("label_birimizhepimizicin_deger")
        self.verticalLayout_44.addWidget(self.label_birimizhepimizicin_deger)
        self.layoutWidget_18 = QtWidgets.QWidget(self.frame_mod)
        self.layoutWidget_18.setGeometry(QtCore.QRect(0, 0, 131, 111))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_aram = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_aram.setFont(font)
        self.label_aram.setObjectName("label_aram")
        self.verticalLayout_40.addWidget(self.label_aram)
        self.label_aram_deger = QtWidgets.QLabel(self.layoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_aram_deger.sizePolicy().hasHeightForWidth())
        self.label_aram_deger.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_aram_deger.setFont(font)
        self.label_aram_deger.setText("")
        self.label_aram_deger.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_aram_deger.setWordWrap(True)
        self.label_aram_deger.setIndent(-1)
        self.label_aram_deger.setObjectName("label_aram_deger")
        self.verticalLayout_40.addWidget(self.label_aram_deger)
        self.buton_ayarlar = QtWidgets.QPushButton(self.frame_info)
        self.buton_ayarlar.setGeometry(QtCore.QRect(550, 320, 41, 41))
        self.buton_ayarlar.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;")
        self.buton_ayarlar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/ayarlar_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buton_ayarlar.setIcon(icon)
        self.buton_ayarlar.setIconSize(QtCore.QSize(21, 21))
        self.buton_ayarlar.setObjectName("buton_ayarlar")
        self.buton_bilgi = QtWidgets.QPushButton(self.frame_info)
        self.buton_bilgi.setGeometry(QtCore.QRect(550, 270, 41, 41))
        self.buton_bilgi.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;")
        self.buton_bilgi.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/simge/image/icon/bilgi_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buton_bilgi.setIcon(icon1)
        self.buton_bilgi.setIconSize(QtCore.QSize(35, 35))
        self.buton_bilgi.setObjectName("buton_bilgi")
        self.buton_cevrimdisi = QtWidgets.QPushButton(self.frame_info)
        self.buton_cevrimdisi.setGeometry(QtCore.QRect(550, 60, 41, 41))
        self.buton_cevrimdisi.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;")
        self.buton_cevrimdisi.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/simge/image/icon/cevrimdisi_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buton_cevrimdisi.setIcon(icon2)
        self.buton_cevrimdisi.setIconSize(QtCore.QSize(30, 30))
        self.buton_cevrimdisi.setObjectName("buton_cevrimdisi")
        self.buton_modlar = QtWidgets.QPushButton(self.frame_info)
        self.buton_modlar.setGeometry(QtCore.QRect(550, 10, 41, 41))
        self.buton_modlar.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;")
        self.buton_modlar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/icon/mod_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buton_modlar.setIcon(icon3)
        self.buton_modlar.setIconSize(QtCore.QSize(28, 28))
        self.buton_modlar.setObjectName("buton_modlar")
        self.buton_samp_arama = QtWidgets.QPushButton(self.frame_info)
        self.buton_samp_arama.setGeometry(QtCore.QRect(550, 110, 41, 41))
        self.buton_samp_arama.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;")
        self.buton_samp_arama.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/icon/arama_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buton_samp_arama.setIcon(icon4)
        self.buton_samp_arama.setIconSize(QtCore.QSize(25, 25))
        self.buton_samp_arama.setObjectName("buton_samp_arama")
        self.frame_ayarlar = QtWidgets.QFrame(self.centralwidget)
        self.frame_ayarlar.setGeometry(QtCore.QRect(20, 410, 781, 101))
        self.frame_ayarlar.setStyleSheet("")
        self.frame_ayarlar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ayarlar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ayarlar.setObjectName("frame_ayarlar")
        self.layoutWidget_24 = QtWidgets.QWidget(self.frame_ayarlar)
        self.layoutWidget_24.setGeometry(QtCore.QRect(70, 10, 80, 31))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.horizontal_dil = QtWidgets.QHBoxLayout(self.layoutWidget_24)
        self.horizontal_dil.setContentsMargins(0, 0, 0, 0)
        self.horizontal_dil.setObjectName("horizontal_dil")
        self.radioButton_tr = QtWidgets.QRadioButton(self.layoutWidget_24)
        self.radioButton_tr.setStyleSheet("")
        self.radioButton_tr.setChecked(True)
        self.radioButton_tr.setObjectName("radioButton_tr")
        self.horizontal_dil.addWidget(self.radioButton_tr)
        self.radioButton_en = QtWidgets.QRadioButton(self.layoutWidget_24)
        self.radioButton_en.setObjectName("radioButton_en")
        self.horizontal_dil.addWidget(self.radioButton_en)
        self.progressBar_veriguncelle = QtWidgets.QProgressBar(self.frame_ayarlar)
        self.progressBar_veriguncelle.setGeometry(QtCore.QRect(220, 60, 551, 31))
        self.progressBar_veriguncelle.setProperty("value", 0)
        self.progressBar_veriguncelle.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_veriguncelle.setInvertedAppearance(False)
        self.progressBar_veriguncelle.setObjectName("progressBar_veriguncelle")
        self.checkBox_otomatikguncelle = QtWidgets.QCheckBox(self.frame_ayarlar)
        self.checkBox_otomatikguncelle.setGeometry(QtCore.QRect(590, 10, 121, 21))
        self.checkBox_otomatikguncelle.setObjectName("checkBox_otomatikguncelle")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_ayarlar)
        self.layoutWidget2.setGeometry(QtCore.QRect(220, 10, 161, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontal_soundchamp = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontal_soundchamp.setContentsMargins(0, 0, 0, 0)
        self.horizontal_soundchamp.setObjectName("horizontal_soundchamp")
        self.buton_sescamp = QtWidgets.QPushButton(self.layoutWidget2)
        self.buton_sescamp.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;")
        self.buton_sescamp.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/simge/image/icon/ses_acik.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buton_sescamp.setIcon(icon5)
        self.buton_sescamp.setIconSize(QtCore.QSize(21, 21))
        self.buton_sescamp.setObjectName("buton_sescamp")
        self.horizontal_soundchamp.addWidget(self.buton_sescamp)
        self.slider_campsound = QtWidgets.QSlider(self.layoutWidget2)
        self.slider_campsound.setMaximum(100)
        self.slider_campsound.setPageStep(20)
        self.slider_campsound.setProperty("value", 50)
        self.slider_campsound.setOrientation(QtCore.Qt.Horizontal)
        self.slider_campsound.setObjectName("slider_campsound")
        self.horizontal_soundchamp.addWidget(self.slider_campsound)
        self.buton_guncelle = QtWidgets.QPushButton(self.frame_ayarlar)
        self.buton_guncelle.setGeometry(QtCore.QRect(460, 10, 111, 23))
        self.buton_guncelle.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(204, 206, 166);\n"
"border-radius: 0px;\n"
"")
        self.buton_guncelle.setObjectName("buton_guncelle")
        self.buton_yuklemedurumu = QtWidgets.QPushButton(self.frame_ayarlar)
        self.buton_yuklemedurumu.setGeometry(QtCore.QRect(730, 0, 41, 41))
        self.buton_yuklemedurumu.setStyleSheet("border-style: outset;\n"
"border-width: 3px;\n"
"border-radius: 0px;\n"
"border-color: rgb(136, 136, 68) ; \n"
"text-align: center ; \n"
"font: 75 9pt \"Microsoft Tai Le\";\n"
"color: rgb(240, 233, 221);\n"
"border-radius: 10px;")
        self.buton_yuklemedurumu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image/icon/ilerleme_kapali.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buton_yuklemedurumu.setIcon(icon6)
        self.buton_yuklemedurumu.setIconSize(QtCore.QSize(28, 28))
        self.buton_yuklemedurumu.setObjectName("buton_yuklemedurumu")
        self.lineEdit_samp_arama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_samp_arama.setGeometry(QtCore.QRect(30, 360, 121, 31))
        self.lineEdit_samp_arama.setStyleSheet("\n"
"    border: 2.2px solid rgb(210, 227, 148);\n"
"    border-radius: 7px;\n"
"    padding: 0 8px;\n"
"    background: transparent;\n"
"    color: rgb(210, 227, 148);\n"
"font: 75 10pt \"Arial\";")
        self.lineEdit_samp_arama.setText("")
        self.lineEdit_samp_arama.setMaxLength(10)
        self.lineEdit_samp_arama.setObjectName("lineEdit_samp_arama")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_mana.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Mana_icon.png\"/> MANA</p></body></html>"))
        self.label_saldirigucu.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Attack_damage_icon.png\"/> SALDIRI GÜCÜ</p></body></html>"))
        self.label_kritiksansi.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Critical_strike_damage_icon.png\"/> KRİTİK VURUŞ ŞANSI</p></body></html>"))
        self.label_harekethizi.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Movement_speed_icon.png\"/>  HAREKET HIZI</p></body></html>"))
        self.label_saldirimenzili.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Range_icon.png\"/> SALDIRI MENZİLİ</p></body></html>"))
        self.label_buyudirenci.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Magic_resistance_icon.png\"/>  BÜYÜ DİRENCİ</p></body></html>"))
        self.label_saldirihiziorani.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Attack_speed_icon.png\"/>  SALDIRI HIZI ORANI</p></body></html>"))
        self.label_temelsaldirihizi.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Attack_speed_icon.png\"/>  TEMEL SALDIRI HIZI</p></body></html>"))
        self.label_manayenileme.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Mana_regeneration_icon.png\"/>  MANA YENİLEME</p></body></html>"))
        self.label_canyenileme.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Health_regeneration_icon.png\"/>  CAN YENİLEME</p></body></html>"))
        self.label_zirh.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Armor_icon.png\"/>  ZIRH</p></body></html>"))
        self.label_secimyaricap.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Selection_radius.png\"/>  SECİM YARIÇAPI</p></body></html>"))
        self.label_edinmeyaricap.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Acquisition_range.png\"/>  EDİNME YARIÇAPI</p></body></html>"))
        self.label_yolyaricap.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Pathing_radius.png\"/>  YOL YARIÇAPI</p></body></html>"))
        self.label_bonussaldirihizi.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Attack_speed_icon.png\"/>  BONUS SALDIRI HIZI</p></body></html>"))
        self.label_saldirisonlandirma.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Attack_speed_icon.png\"/>  SALDIRI SONLANDIRMA</p></body></html>"))
        self.label_oyunyaricap.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Gameplay_radius.png\"/>  OYUN YARIÇAPI</p></body></html>"))
        self.label_can.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/simge/image/icon/Health_icon.png\"/>  CAN</p></body></html>"))
        self.label_arena.setText(_translate("MainWindow", "ARENA"))
        self.label_nexusblitz.setText(_translate("MainWindow", "NEXUS BLİTZ"))
        self.label_ultibuyukitabi.setText(_translate("MainWindow", "ULTİ BÜYÜ KİTABI"))
        self.label_urf.setText(_translate("MainWindow", "URF"))
        self.label_birimizhepimizicin.setText(_translate("MainWindow", "BİRİMİZ HEPİMİZ İÇİN"))
        self.label_aram.setText(_translate("MainWindow", "ARAM"))
        self.radioButton_tr.setText(_translate("MainWindow", "TR"))
        self.radioButton_en.setText(_translate("MainWindow", "EN"))
        self.checkBox_otomatikguncelle.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.checkBox_otomatikguncelle.setText(_translate("MainWindow", "Otomatik Güncelle"))
        self.buton_guncelle.setText(_translate("MainWindow", "Manuel Güncelle"))
import image_koleksiyon_rc
